### ISSUE TITLE
[Question] How to use this from the Saxon command line?

### ISSUE THREAD

**Issue by bmix** [ndw/sinclude#2]
Hello,

thank you so much for your continuos output of XML tools! :-)

Not an issue, just a question.

Experimenting, how XIncludes could help modularizing POM development, I ran an XSLT3 identity-transform to build the final POM:

```xsl
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:mode on-no-match="deep-copy"/>

  <xsl:template match="/">
    <xsl:apply-templates/>
  </xsl:template>

</xsl:stylesheet>
```
with
```
Saxon-HE 10.5J from Saxonica
Java version 16.0.1
Using parser org.xmlresolver.tools.ResolvingXMLReader
```

using the `-xi:on` option, but the only way I was successful, was by not using any `@xpointer` at all and instead just including the whole fragment file with a simple `@href`.

I would prefer using *sinclude*, but don't know, whether I can tell Saxon, on the command-line, to use this processor. Btw: I use your *JavaConfig* with the following settings:

```xml
<java xml:id="java" exec="C:\Program Files (x86)\OpenJDK\jdk-16.0.1\bin\java.exe">
  <java-option name="XX:+HeapDumpOnOutOfMemoryError"/>
</java>

<saxon xml:id="saxon" extends="java">
  <maven artifact="org.xmlresolver:xmlresolver:3.1.0"/>
</saxon>

<saxon xml:id="saxon-9" extends="saxon" class="net.sf.saxon.Transform" argsep=":">
  <arg name="x" value="org.xmlresolver.tools.ResolvingXMLReader"/>
  <arg name="y" value="org.xmlresolver.tools.ResolvingXMLReader"/>
  <arg name="r" value="org.xmlresolver.Resolver"/>
</saxon>

<saxon xml:id="saxon-10he" extends="saxon-9">
  <maven artifact="net.sf.saxon:Saxon-HE:10.5"/>
  <maven artifact="org.apache.logging.log4j:log4j-api:2.1"/>
  <maven artifact="org.apache.logging.log4j:log4j-core:2.1"/>
  <maven artifact="org.apache.logging.log4j:log4j-slf4j-impl:2.1"/>
  <maven artifact="org.slf4j:jcl-over-slf4j:1.7.10"/>
  <maven artifact="org.slf4j:slf4j-api:1.7.10"/>
  <maven artifact="org.apache.httpcomponents:httpclient:4.5.2"/>
  <maven artifact="org.apache.httpcomponents:httpcore:4.4.5"/>
  <maven artifact="org.apache.httpcomponents:httpmime:4.5.8"/>
</saxon>

<saxon xml:id="saxon-10hexi" extends="saxon-10he">
  <arg name="xi" value="on" />
</saxon>
```

Any advice? 

Thank you.

**Comment by bmix** [comment]
Sorry, I just saw the instruction in the readme!

**Comment by bmix** [comment]
I was wrong. The command line switch was for registering the XSL extension function. So I still have the question.

**Comment by ndw** [comment]
I use it by calling the extension function explicitly where I want XInclude processing to be performed. For example, [in the DocBook xslTNG stylesheets](https://github.com/docbook/xslTNG/blob/main/src/main/xslt/transforms/10-xinclude.xsl).

Making Saxon use it automatically with a command line option  isn't something I've considered. But I'll take a look.

**Comment by bmix** [comment]
Thank you. Since you mentioned, that you may want to look into further action, I keep the issue open.
